# Generated by Django 5.2.17 on 2026-09-19 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitors', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='monitor',
            old_name='create_at',
            new_name='created_at',
        ),
    ]
