# Generated by Django 5.2.17 on 2026-09-22 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitors', '0003_incident'),
    ]

    operations = [
        migrations.AddField(
            model_name='monitor',
            name='expected_status',
            field=models.CharField(default='200-299', help_text="Comma-separated codes or ranges considered 'up', e.g. 200-299,401", max_length=50),
        ),
    ]
