# Generated by Django 5.2.17 on 2026-09-22 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitors', '0004_monitor_expected_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='monitor',
            name='keyword',
            field=models.CharField(blank=True, help_text="Optional. If set, the response body must contain this text to count as 'up'.", max_length=200),
        ),
    ]
