# Generated by Django 5.2.17 on 2026-09-22 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitors', '0005_monitor_keyword'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monitor',
            name='url',
            field=models.CharField(max_length=500),
        ),
    ]
